apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app-web
        image: dockerprithvi/blog-app:latest
        ports:
          - containerPort: 80
      imagePullSecrets:
          - name: blog-app-secret
