apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog-app
  name: blog-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      type: ClusterIP
  selector:
    app: blog-app
