# Generated by Django 4.2.15 on 2024-09-03 07:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
