# Generated by Django 4.2.15 on 2024-09-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("blog_app", "0002_alter_blogpost_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="users.profile",
            ),
            preserve_default=False,
        ),
    ]
